### ISSUE TITLE
Error with docker

### ISSUE THREAD

**Issue by raymand211092** [roborg-codes/telegram-mastodon-bridge#5]
Traceback (most recent call last):
  File "./bot.py", line 6, in <module>
    from bridge.bridge import Bridge
  File "/bot/bridge/bridge.py", line 16, in <module>
    class Bridge():
  File "/bot/bridge/bridge.py", line 84, in Bridge
    def __send_status(self, text: List[str], media: Optional[str | bytes] = None, mime: Optional[str] = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Mrs-Feathers** [comment]
i have this same issue. were you able to solve it?
